---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_version: 2.2.0.0
  require_pip: true

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: master
    driver:
      network:
        - ["private_network", { ip: "172.29.129.172" }]

  - name: slave
    driver:
      network:
        - ["private_network", { ip: "172.29.129.191" }]
