---

- name: Create jobdsl dir for dslscriptloader.groovy
  file:
    path:  "{{ jenkins_jobdsl_scripts_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
    state: directory

- name: Copy jobdsl scripts for dslscriptloader.groovy
  template:
    src:   "{{ item }}"
    dest:  "{{ jenkins_jobdsl_scripts_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0644
  with_items:
    "{{ jenkins_jobdsl_scripts }}"

# https://wiki.jenkins-ci.org/display/JENKINS/Post-initialization+script
- name: Create jenkins post-initialization scripts dir
  file:
    path:  "{{ jenkins_post_init_scripts_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
    state: directory

- name: Copy jenkins post-init scripts
  copy:
    src:   "{{ item }}"
    dest:  "{{ jenkins_post_init_scripts_dir }}/{{ item }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
  with_items:
    - dslscriptloader.groovy
    - add-global-environment-variables.groovy
  notify: Restart jenkins

- name: Copy and Parse jenkins post-init script templates
  template:
    src:   "{{ item }}.j2"
    dest:  "{{ jenkins_post_init_scripts_dir }}/{{ item }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
  with_items:
    - executors.groovy
    - set_slave_agent_port.groovy
  notify: Restart jenkins

# Trigger any pending restart handlers now so that post-init scripts can run
# after Jenkins starts up. This is necessary for jenkins-cli commands to work
- meta: flush_handlers

- name: Wait for jenkins to be available
  uri:
    url:  "http://localhost:{{ jenkins_http_port }}/login"
  register: resp
  until: resp.status|default(false) == 200
  retries: 10
  delay: 10
